### ISSUE TITLE
Free Pascal: inlining is not turned on

### ISSUE THREAD

**Issue by edkachalov** [greensoftwarelab/Energy-Languages#13]
The Free Pascal code using the inline functions, but inlining is off.
Here is the [documentation](https://www.freepascal.org/docs-html/ref/refsu73.html) about this feature:

> By default, inline procedures are not allowed. Inline code must be enabled using the command-line switch -Si or {$inline on} directive.

So there are two possible decisions:
1. Add **{$inline ON}** into the begining of source code;
2. Add **-Si** switch into makefile.

**Comment by MarcoCouto** [comment]
Hi @edkachalov. 

The Pascal code and the compile/run options were obtained from the Computer Language Benchmarks Game [(CLBG)](https://benchmarksgame-team.pages.debian.net/benchmarksgame/). To the best of our knowledge, the code and the compile/run options where provided to the CLBG by expert Pascal programmers. 
This is also true for every other language we included.

If you believe this alteration can greatly influence the efficiency of the solutions, you can open a Pull Request, we can test it and show the results. If the results are good, we'll accept the PR.

Thank you.

**Comment by edkachalov** [comment]
Can't fully use GIT now, but I made the necessary changes.
ZIP contains files that I only changed (I have added only one line to each file, this will not break anything).
Put the content of ZIP into **Pascal** directory and replace the original files.
[InlineON.zip](https://github.com/greensoftwarelab/Energy-Languages/files/2325498/InlineON.zip)

**Comment by MarcoCouto** [comment]
It's easier if you just do a PR. That way we can keep track of who contributed to the repository.
Feel free do do it whenever you can.
