### ISSUE TITLE
Provide a legend for generated csv files 

### ISSUE THREAD

**Issue by meehew** [greensoftwarelab/Energy-Languages#16]
Hello,
I have decided to run the experiment by myself, however I can't figure out what the data generated in the {language}.csv is. Mind helping me out?

**Comment by States** [comment]
Hey there,

each {language}.csv will contain a line with the following:

benchmark-name ; PKG (Joules) ; CPU (J) ; GPU (J)  ; DRAM (J) ; Time (ms)

Do note that the availability of GPU/DRAM measurements depend on your machine's architecture. These are requirements from RAPL itself.

cheers!

**Comment by meehew** [comment]
Thank you so much!
