### ISSUE TITLE
results of the energy measurements are all zeros

### ISSUE THREAD

**Issue by xz328** [greensoftwarelab/Energy-Languages#24]
Hi, 

I am running the energy measurements benchmark tests for Python. The tests are run on a Coffee Lake CPU (CPU model is 158). Since this specific model is not included in the supported 5 models in the rapl.c file, I overwrote the model read it from my computer to force it to be 60, e.g., HASWELL. Then, I recompile it to get the main binary.

In the result CSV file (Python.csv), **all the metrics I got are zeros** except the execution time, i.e., the last column, as shown below.

![image](https://user-images.githubusercontent.com/49292972/124665812-19dfce80-dea5-11eb-939c-0985420527cb.png)

Does anyone get a similar issue? Could this be caused by the changes I made to the rapl.c file? If so and I have only the Coffee Lake CPU which is not in the supported CPUs, is there a way I can run the measurements anyway?

Thanks, 

Aaron

**Comment by States** [comment]
Hello Aaron, sorry for the very late response. I have updated the the RAPL file up to Kabylake (CPU model 158). I assume CoffeeLake is some sub-Kabylake model to have the same code. 

Do also note you should be on Linux (which by the terminal, it looks like it already), and have to first run:
`sudo modprobe msr`
Prior to executing anything RAPL based.

This seems to be missing in the read.me for the main page, so I am also updating that now too. 

Let me know if you still have issues!
