### ISSUE TITLE
Add LuaJIT to the benchmark.

### ISSUE THREAD

**Issue by DNS** [greensoftwarelab/Energy-Languages#26]
Add LuaJIT (not Lua) to the benchmark. 
It's very fast, should be at similar speed like C.

**Comment by States** [comment]
This repository contains the replication artefact package for our published 2017 paper using these. They were based on the contents and compilers running on CLBG at the time, thus we too used Lua (5.3.3 as was used at the time). Feel free to fork the repo and run your own tests as you wish however!

**Comment by DNS** [comment]
[Compiler / Interpreter versions](https://sites.google.com/view/energy-efficiency-languages/setup?authuser=0)
I see only **Lua 5.3.3**, but no **LuaJIT**?
Do you think Lua is the same as LuaJIT?
