### ISSUE TITLE
Use Better C# Framework

### ISSUE THREAD

**Issue by dogac00** [greensoftwarelab/Energy-Languages#28]
Hi,

As far as I can see, C# benchmarks are using .NET Core 1.1, which is released in 2017. There were many upgrades to this version over the years. I think using .NET 1.1 as C# can be misrepresenting because we can consider .NET Core 1.1 as an experimental version for cross-platform C# and there are many improvements made to .NET framework. The latest one is currently .NET 6. Performance is much better in the newer frameworks.

I think using .NET 5 or .NET 6 will better represent C# community here.

Thank you,
Dogac

**Comment by States** [comment]
This repository is the replication artefact for our publication which came out in 2017, hence why we are using a 2017 version here :) Feel free to fork the repo and update to your needs if you wish to run some more modern tests however.
