### ISSUE TITLE
Resource LFS overquota

### ISSUE THREAD

**Issue by turric4n** [greensoftwarelab/Energy-Languages#7]
Hi,

I can't not pull large resource files doing : git lfs pull

Error message : This repository is over its data quota. Purchase more data packs to restore access.

Can we find this files on another location?

**Comment by States** [comment]
Hey there,

You can generate the input files using one of the **fasta** programs.

For the knucleotide-input25000000.txt: using one of the **fasta** programs with command line arguments: 25000000 > knucleotide-input25000000.txt

For the regexredux-input5000000.txt: using one of the **fasta** programs with command line arguments: 5000000 > regexredux-input5000000.tx

For the revcomp-input25000000.txt: using one of the **fasta** programs with command line arguments: 25000000 > revcomp-input25000000.txt

**Comment by turric4n** [comment]
Seems a good idea :) 👍  Thanks you very much!
